//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetTelematics.Facades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telemetry
    {
        public int Id { get; set; }
        public int FkTruckId { get; set; }
        public Nullable<decimal> OilPressure { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Truck Truck { get; set; }
    }
}
